package actions

import (
	
)
const (
PLAYER_HEALTH = 100
MONSTER_HEALTH = 100
MIN_ATTACK_DMG = 5
MAX_ATTACK_DMG = 10
MIN_SPECIAL_ATTACK = 10
MAX_SPECIAL_ATTACK = 20
MIN_MONSTER_ATTACK_DMG = 9
MAX_MONSTER_ATTACK_DMG = 14
MIN_HEAL = 10
MAX_HEAL = 15
)